### ISSUE TITLE
Packet: Feature Request: Consider enabling multipathd by default

### ISSUE THREAD

**Issue by DGollings** [kinvolk/lokomotive-kubernetes#129]
At least for packet, both the [Packet CSI driver](https://github.com/packethost/csi-packet) and their [object storage scripts](https://www.packet.com/resources/guides/elastic-block-storage/) rely on it running.

I've fixed it with a CLC_snippet, but figured it would be worth mentioning.

Great scripts btw, thanks

The working snippet:
```
# Required for CSI driver
systemd:
  units:
    - name: multipathd.service
      enable: true
```
