### ISSUE TITLE
Linkerd installation broken - no apiserver client ca file

### ISSUE THREAD

**Issue by DGollings** [kinvolk/lokomotive-kubernetes#148]
Good and bad news, I believe one of your recent commits broke Linkerd (and probably similarly architected applications)

The good news is that I think I've narrowed it down to a very likely candidate:
3283579af4e5a21383e89036e1bec2ae3d7d37ce

And I also think I know what's missing:
`kubectl -n kube-system get cm/extension-apiserver-authentication -ojsonpath='{.data.requestheader-client-ca-file}'`

And here's a hint as to where or what needs to be fixed/added:
[github.com/kubernetes-sigs/bootkube/issues/994](https://github.com/kubernetes-sigs/bootkube/issues/994#issuecomment-405647649)

Hope this helps

Steps to reproduce:
start a fresh cluster
```
curl -sL https://run.linkerd.io/install | sh
export PATH=$PATH:$HOME/.linkerd2/bin
linkerd install | kubectl apply -f -
#Kill it after a couple minutes, it'll never boot. Check
kubectl get pods -n linkerd
# and you'll see linkerd-tap crashing
```

**Comment by DGollings** [comment]
going back to 56acc133cddedd8756deebb01fe9be196c0cfb99 fixed it, forgot to mention that

**Comment by surajssd** [comment]
I was able to reproduce the problem.

Here is the cluster from the latest master:

```console
$ kubectl get nodes
NAME                            STATUS   ROLES    AGE     VERSION
suraj-cluster-controller-0      Ready    <none>   8m54s   v1.17.2
suraj-cluster-helium-worker-0   Ready    <none>   9m15s   v1.17.2
suraj-cluster-helium-worker-1   Ready    <none>   9m14s   v1.17.2
suraj-cluster-helium-worker-2   Ready    <none>   9m1s    v1.17.2
```

and the linkerd version from the latest stable:

```console
$ linkerd version
Client version: stable-2.6.1
Server version: unavailable
```

Installing linkerd

```console
$ linkerd install | kubectl apply -f -
namespace/linkerd created
clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-identity created
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-identity created
serviceaccount/linkerd-identity created
clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-controller created
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-controller created
serviceaccount/linkerd-controller created
clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-destination created
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-destination created
serviceaccount/linkerd-destination created
role.rbac.authorization.k8s.io/linkerd-heartbeat created
rolebinding.rbac.authorization.k8s.io/linkerd-heartbeat created
serviceaccount/linkerd-heartbeat created
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-web-admin created
serviceaccount/linkerd-web created
customresourcedefinition.apiextensions.k8s.io/serviceprofiles.linkerd.io created
customresourcedefinition.apiextensions.k8s.io/trafficsplits.split.smi-spec.io created
clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-prometheus created
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-prometheus created
serviceaccount/linkerd-prometheus created
serviceaccount/linkerd-grafana created
clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-proxy-injector created
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-proxy-injector created
serviceaccount/linkerd-proxy-injector created
secret/linkerd-proxy-injector-tls created
mutatingwebhookconfiguration.admissionregistration.k8s.io/linkerd-proxy-injector-webhook-config created
clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-sp-validator created
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-sp-validator created
serviceaccount/linkerd-sp-validator created
secret/linkerd-sp-validator-tls created
validatingwebhookconfiguration.admissionregistration.k8s.io/linkerd-sp-validator-webhook-config created
clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-tap created
clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-tap-admin created
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-tap created
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-tap-auth-delegator created
serviceaccount/linkerd-tap created
rolebinding.rbac.authorization.k8s.io/linkerd-linkerd-tap-auth-reader created
secret/linkerd-tap-tls created
apiservice.apiregistration.k8s.io/v1alpha1.tap.linkerd.io created
podsecuritypolicy.policy/linkerd-linkerd-control-plane created
role.rbac.authorization.k8s.io/linkerd-psp created
rolebinding.rbac.authorization.k8s.io/linkerd-psp created
configmap/linkerd-config created
secret/linkerd-identity-issuer created
service/linkerd-identity created
deployment.apps/linkerd-identity created
service/linkerd-controller-api created
service/linkerd-destination created
deployment.apps/linkerd-controller created
service/linkerd-dst created
deployment.apps/linkerd-destination created
cronjob.batch/linkerd-heartbeat created
service/linkerd-web created
deployment.apps/linkerd-web created
configmap/linkerd-prometheus-config created
service/linkerd-prometheus created
deployment.apps/linkerd-prometheus created
configmap/linkerd-grafana-config created
service/linkerd-grafana created
deployment.apps/linkerd-grafana created
deployment.apps/linkerd-proxy-injector created
service/linkerd-proxy-injector created
service/linkerd-sp-validator created
deployment.apps/linkerd-sp-validator created
service/linkerd-tap created
deployment.apps/linkerd-tap created
```

And the pod fails as mentioned above:

```console
$ kubectl get pods -n linkerd
NAME                                      READY   STATUS             RESTARTS   AGE
linkerd-controller-5b6c98b4d5-krblm       2/3     Running            0          80s
linkerd-destination-74f7c8c4f-jpkqf       0/2     Init:0/1           0          78s
linkerd-grafana-c6867c49-zcq9f            1/2     Running            0          70s
linkerd-identity-5d4f779d84-ptlbx         2/2     Running            0          83s
linkerd-prometheus-5b7f4bc85b-4m4vm       1/2     Running            0          73s
linkerd-proxy-injector-64b4f7b6d7-q66qg   1/2     Running            0          69s
linkerd-sp-validator-7c695984b-p7fxl      0/2     Init:0/1           0          66s
linkerd-tap-5ff8b5cf49-spsw6              0/2     CrashLoopBackOff   3          65s
linkerd-web-5fb56fcf94-msjnf              1/2     Running            0          76s
```

Here is the error from the pod:

```console
$ kubectl -n linkerd logs linkerd-tap-5ff8b5cf49-spsw6 tap
time="2020-01-23T14:17:37Z" level=info msg="running version stable-2.6.1"
time="2020-01-23T14:17:37Z" level=info msg="Using cluster domain: cluster.local"
time="2020-01-23T14:17:37Z" level=fatal msg="no client CA cert available for apiextension-server"
```

The culprit is the apiserver:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: kube-apiserver
    tier: control-plane
  name: kube-apiserver
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: kube-apiserver
      tier: control-plane
  template:
    metadata:
      annotations:
        checkpointer.alpha.coreos.com/checkpoint: "true"
        seccomp.security.alpha.kubernetes.io/pod: docker/default
      creationTimestamp: null
      labels:
        k8s-app: kube-apiserver
        tier: control-plane
    spec:
      containers:
      - command:
        - /hyperkube
        - kube-apiserver
        - --advertise-address=$(POD_IP)
        - --allow-privileged=true
        - --anonymous-auth=false
        - --authorization-mode=RBAC
        - --bind-address=0.0.0.0
        - --client-ca-file=/etc/kubernetes/secrets/ca.crt
        - --cloud-provider=
        - --enable-admission-plugins=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultTolerationSeconds,DefaultStorageClass,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,Priority,PodSecurityPolicy
        - --etcd-cafile=/etc/kubernetes/secrets/etcd-client-ca.crt
        - --etcd-certfile=/etc/kubernetes/secrets/etcd-client.crt
        - --etcd-keyfile=/etc/kubernetes/secrets/etcd-client.key
        - --etcd-servers=https://suraj-cluster-etcd0.dev.lokomotive-k8s.net:2379
        - --insecure-port=0
        - --kubelet-client-certificate=/etc/kubernetes/secrets/apiserver.crt
        - --kubelet-client-key=/etc/kubernetes/secrets/apiserver.key
        - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname[--proxy-client-cert-file=/etc/kubernetes/secrets/aggregation-client.crt
          --proxy-client-key-file=/etc/kubernetes/secrets/aggregation-client.key --requestheader-client-ca-file=/etc/kubernetes/secrets/aggregation-ca.crt
          --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group
          --requestheader-username-headers=X-Remote-User]
        - --secure-port=6443
        - --service-account-key-file=/etc/kubernetes/secrets/service-account.pub
        - --service-cluster-ip-range=10.3.0.0/16
        - --storage-backend=etcd3
        - --tls-cert-file=/etc/kubernetes/secrets/apiserver.crt
        - --tls-private-key-file=/etc/kubernetes/secrets/apiserver.key
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: k8s.gcr.io/hyperkube:v1.17.2
        imagePullPolicy: IfNotPresent
        name: kube-apiserver
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/kubernetes/secrets
          name: secrets
          readOnly: true
        - mountPath: /etc/ssl/certs
          name: ssl-certs-host
          readOnly: true
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        node.kubernetes.io/master: ""
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccount: kube-apiserver
      serviceAccountName: kube-apiserver
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      volumes:
      - name: secrets
        secret:
          defaultMode: 420
          secretName: kube-apiserver
      - hostPath:
          path: /usr/share/ca-certificates
          type: ""
        name: ssl-certs-host
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 1
  desiredNumberScheduled: 1
  numberAvailable: 1
  numberMisscheduled: 0
  numberReady: 1
  observedGeneration: 1
  updatedNumberScheduled: 1
```

Specifically look at all the aggregation flags are garbled:

```yaml
        - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname[--proxy-client-cert-file=/etc/kubernetes/secrets/aggregation-client.crt
          --proxy-client-key-file=/etc/kubernetes/secrets/aggregation-client.key --requestheader-client-ca-file=/etc/kubernetes/secrets/aggregation-ca.crt
          --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group
          --requestheader-username-headers=X-Remote-User]
        - --secure-port=6443
```
